---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: mc-server
          image: itzg/minecraft-bedrock-server
          ports:
            - containerPort: 19132
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - mountPath: /data
              name: mc-data
          tty: true
          stdin: true
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: mc-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector:
    app: minecraft-server
  ports:
    - protocol: UDP
      port: 19132
      targetPort: 19132
  type: LoadBalancer
